name: "Run typechecking on the codebase"
# **What it does**: performs typechecking on the codebase using tsc --noEmit

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  typecheck:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17.9.0

      - name: Install
        run: npm install

      - name: generate prisma client
        run: DATABASE_URL='file:./testing_db.sqlite' npm run migrate -- --name testing_name

      - name: Run typechecking on the repository
        run: npm run tc
